.TH DIRNAME 1 "3rd of August 2026" zenithutils "User Commands"

.SH NAME
dirname - print parent directory of given path

.SH SYNOPSIS
\fBdirname\fP \fIpath\fP

.SH DESCRIPTION
prints the parent directory of a given path, ususally the path itself stripped from its last component

.SH OPTIONS
not applicable
