.TH DOS2UNIX 1 "31st of July 2026" zenithutils "User Commands"

.SH NAME
dos2unix - convert CRLF (DOS/Windows) line endings into LF (Unix)

.SH SYNOPSIS
\fBdos2unix\fP \fI[file] [file2] ...\fP

.SH DESCRIPTION
Convert CRLF line endings into LF line endings, by stripping every carriage return CR byte.
If no file is provided, assume standard input and output

.SH OPTIONS
Not applicable

.SH SEE ALSO
unix2dos(1)
