.TH REV 1 "30th of July 2026" zenithutils "User Commands"

.SH NAME
\fBrev\fP - reverse lines in file

.SH SYNOPSIS 
\fBrev\fP [file] [file2] ...

.SH DESCRIPTION
Reverses a file's lines, line by line.
If no input file is provided or is '-', assume stdin

.SH EXAMPLES
.EX
  $ echo 'xyz' | rev
  zyx
.EE

.SH OPTIONS
not applicable
