.TH RMDIR 1 "5th of August 2026" zenithutils "User Commands"

.SH NAME
rmdir - remove a directory

.SH SYNOPSIS
\fBrmdir\fP [-pv] directory [...]

.SH DESCRIPTION
\fBrmdir\fP will remove a directory / directories specfied via arguments.
The directory must be empty

.SH OPTIONS
.TP
\fB-v\fP
verbose mode, say when a directory was removed

.TP
\fB-p\fP
recursively delete empty parent directories

.SH SEE ALSO
rmdir(2)
