.TH RNG 1 "28th of July 2026" "zenithutils" "User Commands"

.SH NAME
rng - generate a random number 

.SH SYNOPSIS
\fBrng\fP \fI[min] max\fP

.SH DESCRIPTION
\fBrng\fP generates a random number between \fBmin\fP and \fBmax\fP.
Default \fBmin\fP is 0

.SH OPTIONS
Not applicable

.SH ADDITIONAL NOTES
.EX
A note on floating point numbers:
Using rng, you can generate floting point numbers with a precision of \fIn\fP by multiplying \fImin\fP and \fImax\fP by 10^n, then dividing the result by 10^n

This oneliner can help:
    $ bc -l <<< "$(rng 1000 6000)/1000"
    2.42700000000000000000
 
Assuming you have the bc calculator installed and bc and rng are both in PATH
.EE
