.TH SHA512SUM 1 "5th of August 2026" zenithutils "User Commands"

.SH NAME
sha512sum - compute the SHA512 hash of input

.SH SYNOPSIS
\fBsha512sum\fP [file]

.SH DESCRIPTION
\fBsha512sum\fP will compute the SHA512 hash of the given input. if \fIfile\fP is not specified, assume standard input.

.SH OPTIONS
not applicable
