.TH TAC 1 "17th of August 2026" zenithutils "User Commands"

.SH NAME
tac - concatenate files in reverse

.SH SYNOPSIS
\fBtac\fP \fI[files]\fP ...

.SH DESCRIPTION
\fBtac\fP concatenates each file passed as arguments, line by line, from the last line to the first

If no argument is provided or argument is '-', tac will read from standard input

.SH OPTIONS
not applicable

.SH SEE ALSO
cat(1), rev(1)
