.TH TRUE 1 "28th of July 2026" "zenithutils" "User Commands"

.SH NAME
true - always succeed, all the time.

.SH SYNOPSIS
.B true

.SH DESCRIPTION
.PP
No matter what, \fBtrue\fP will exit with code 0 (which indicates success)
.PP
Note: This program may possibly never run, given it is usually built into the shell

.SH OPTIONS
No options
