.TH UNAME 1 "5th of August 2026" zenithutils "User Commands"

.SH NAME
uname - print system information

.SH SYNPOSIS
\fBuname\fP \fI[-asnrvmpio]\fP

.SH DESCRIPTION
\fBuname\fP print various information about the current system

.SH OPTIONS
.TP
\fB-s\fP
print kernel name

.TP
\fB-n\fP
print hostname

.TP
\fB-r\fP
print kernel release

.TP
\fB-v\fP
print kernel version

.TP
\fB-m, -p, -i\fP
print system processor architecture

.TP
\fB-o\fP
print operating system name

.TP
\fB-a\fP
shorthand for all of the above options

.PP
Note: \fB-s\fP is the default if no option is specified

.SH SEE ALSO
uname(2)
