.TH XARGS 1 "17th of August 2026" zenithutils "User Commands"

.SH NAME
xargs - extract command line arguments and execute commands

.SH SYNOPSIS
\fBxargs\fP \fIcommand [...]\fP

.SH DESCRIPTION
\fBxargs\fP runs a program specified by \fIcommand\fP and builds arguments for it based on its first arguments \fI'...'\fP and then arguments from standard input, separated by either a space ' ', newline '\\n', or horizontal tab '\\t'

.SH OPTIONS
not applicable

.SH EXAMPLES
.EX
    $ # note: which separates by newline '\\n'
    $ which ls sh | xargs file
    /sbin/ls: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), ...
    /sbin/sh: symbolic link to dash
.EE

