.TH YES 1 "28th of July 2026" zenithutils "User Commands"

.SH NAME
yes - repeated output of a string

.SH SYNPOSIS
\fByes\fP \fI[expletive]\fP

.SH DESCRIPTION
.PP
\fByes\fP repeatedly outputs a given string (called an expletive).
.PP
If no expletive is provided, the letter 'y' will be used as a default expletive

.SH OPTIONS
No options
